stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/postgres-cron:v1
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
